# Generated by Django 3.1.7 on 2021-03-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
