# Generated by Django 3.1.7 on 2021-03-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_steamuser_last_verify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='is_approved_to_group',
            field=models.BooleanField(default=False),
        ),
    ]
